# -*- coding: utf-8 -*-
"""GCA practice Journey begins

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12QEjva3MwwZGJFJQo6re_c_1nTARMi4r

Write a function that returns the sum of two numbers.

Example

For param1 = 1 and param2 = 2, the output should be
solution(param1, param2) = 3.
"""

#write a function
#in the function return a + b 
#the params of the function are a and b
def sum_two_nums(a,b):
  return a + b

#call the function with numbers for the parameters
sum_two_nums(13,2127)

#===============================================================================================
#===============================================================================================
#===============================================================================================
#===============================================================================================
#===============================================================================================
#===============================================================================================
#===============================================================================================
#===============================================================================================
#===============================================================================================

"""Given a year, return the century it is in. The first century spans from the year 1 up to and including the year 100, the second - from the year 101 up to and including the year 200, etc.

Example

For year = 1905, the output should be
solution(year) = 20;
For year = 1700, the output should be
solution(year) = 17.
"""

#you will be given a random date and you must tell me what century it is in
# ex) input 1905 = 20
# ex) input 1700 = 17
def year_to_cent(a):
  return (a+100) // 100

year_to_cent(1905)
#pass

year_to_cent(1700)
#fail

#why did the second test fail?
#1700 is the end of the 17th century and not the beginning of the 18th
#1700 + 100 bring it to 18 in stead of staying in 17 so we will add 99 instead

#NEW FUNCTION
def year_to_cent(a):
  return (a+99) // 100

year_to_cent(1905)
#pass

year_to_cent(1700)
#pass

#===============================================================================================
#===============================================================================================
#===============================================================================================
#===============================================================================================
#===============================================================================================
#===============================================================================================
#===============================================================================================
#===============================================================================================
#===============================================================================================

"""Given the string, check if it is a palindrome.

Example

For inputString = "aabaa", the output should be
solution(inputString) = true;
For inputString = "abac", the output should be
solution(inputString) = false;
For inputString = "a", the output should be
solution(inputString) = true.
"""

#create function

#the function will check if a string is the same as the backward verion [::-1] of its self.

#return true or false 
def solution(a):
  return a == a[::-1]

solution('aabbaa')

solution('bbjhdkwjd')

solution('111222333333222111')

#passing all tests

